import { InHouseTypes } from "@/types/BasicTypes";
import { debugData } from "@/utils/debugData";

debugData([
  {
    action: "ui:setupUI",
    data: {
      setDefaultHouses: {
        [1]: {
          houseId: 1,
          label: "De Santa Residence",
          coords_label: "Portola Drive, Rockford Hills",
          price: 5999999,
          type: "furnished",
          meta: {},
        },
        [2]: {
          houseId: 1,
          label: "De Santa Residence",
          coords_label: "Portola Drive, Rockford Hills",
          price: 5999999,
          type: "furnished",
          meta: {},
        },
        [3]: {
          houseId: 1,
          label: "De Santa Residence",
          coords_label: "Portola Drive, Rockford Hills",
          price: 5999999,
          type: "furnished",
          meta: {},
        },
        [4]: {
          houseId: 1,
          label: "De Santa Residence",
          coords_label: "Portola Drive, Rockford Hills",
          price: 5999999,
          type: "furnished",
          meta: {},
        },
        [5]: {
          houseId: 1,
          label: "De Santa Residence",
          coords_label: "Portola Drive, Rockford Hills",
          price: 5999999,
          type: "furnished",
          meta: {},
        },
        [6]: {
          houseId: 1,
          label: "De Santa Residence",
          coords_label: "Portola Drive, Rockford Hills",
          price: 5999999,
          type: "furnished",
          meta: {},
        },
      },
      setSoldHouses: [],
      setHasDlc: {
        [1]: {
          dlc: "weed",
          value: true,
        },
      },
      setIndicatorSettings: {
        electricity: {
          maxValue: 999,
          unitPrice: 8,
        },
        power: {
          maxValue: 999,
          unitPrice: 8,
        },
        water: {
          maxValue: 999,
          unitPrice: 8,
        },
        gas: {
          maxValue: 999,
          unitPrice: 8,
        },
      },
      setHouseTypes: {
        ["square"]: {
          label: "Square",
        },
        ["rectangle"]: {
          label: "Rectangle",
        },
        ["furnished"]: {
          label: "Furnished",
        },
        ["test"]: {
          label: "Test",
        },
      },
      setLocale: {
        locale: "en",
        languages: {
          available_houses: "Available houses",
          attention: "Attention",
          desc_attention:
            "Before buying check documents of seller and about house!",
          price: "Price",
          you_buying_house: "You are buying house",
          market_price: "Market Price",
          purchase: "Purchase",
          cancel: "Cancel",
          house: "House",
          security: "Security",
          setup: "Setup",
          your: "your",
          house_system: "House System",
          wall_color: "Wall Color",
          customize_your_walls: "Customize your walls",
          customize_your_house: "Customize your house",
          stairs: "Stairs",
          add_or_remove_stairs: "Add or remove stairs",
          on: "ON",
          off: "OFF",
          lights: "Lights",
          furniture: "Furniture",
          cctv: "CCTV",
          desc_cctv: "Open CCTV Channel",
          toggle_lights: "Toggle Lights",
          indicators: "Indicators",
          electricity: "Electricity",
          power: "Power",
          gas: "Gas",
          water: "Water",
          permissions: "Permissions",
          desc_permissions: "Change neighboors permissions",
          player_id: "Player Id",
          search: "Search",
          add: "Add",
          guest: "Guest",
          owner: "Owner",
          square: "Square",
          rectangle: "Rectangle",
          furnished: "Furnished",
          type: "Type",
          out: "Out",
          moved_out: "Moved Out",
          desc_moved_out: "Leave the house permanently",
          double_click: "Double Click",
          owner_transfer: "House Transfer",
          desc_transfer: "Transfer ownership of your home.",
          money_type: "$",
          choose_player: "Choose a player",
          transfer: "Transfer",
          design_seed: "Design Seed",
          desc_design_seed: "Use/Generate design seed.",
          use: "Use",
          generate: "Generate",
          seed: "Seed...",
          shop: "Shop",
          desc_shop: "You can refill your energy stores by buying them.",
          unit_x_money: "Unit {{unit}} {{money_type}}",
          desc_shop_buy: "Each time you buy 100 units. {{unit}}",
          visit_house: "Visit House",
          create_new_house: "Create New House",
          desc_new_house: "Quickly create a new house",
          create: "Create",
          door_coords: "Door Coords",
          garage_coords: "Garage Coords",
          label: "Label",
          coords_label: "Coords Label",
          garage_wall_color: "Garage Wall Color",
          DLC_Weed: "DLC: Weed",
          desc_buy_dlc: "Buy DLC to unlock this",
          rooms: "Rooms",
          add_or_remove_rooms: "Add or remove rooms",
          can_choose_player: "Player can choose",
          image: "Image",
          lFurniture: {
            switch_mode: "Switch to {{mode}} Mode",
            snap_ground: "Snap To Ground",
            finish_editing: "Finish Editing",
            save: "Save",
            furniture_list: "Furniture List",
            desc_furniture_list: "Objects you can place or own.",
            input_search: "Search by name...",
            purchase: "Purchase",
            owned: "Owned",
            edit_furniture: "Edit Furniture",
            put_in_storage: "Put in Storage",
            place_on_ground: "Place on Ground",
            object_settings: "Object Settings",
            desc_object_settings: "Fine tune your placed object.",
            back_to_owned: "Back to Owned",
            resell: "Re-sell",
            delete_object: "Delete Object",
            desc_enter_del:
              "For [Enter] and [Del] you need to focus on the game!",
            camera_move: "Camera Move",
            camera_rotation: "Camera Rotation",
            placed: "Placed",
            back: "Back",
          },
        },
      },
      setWallColors: [
        { id: 1, color: "#FFFFFF" },
        { id: 2, color: "#747474" },
        { id: 3, color: "#232323" },
        { id: 4, color: "#351B7D" },
        { id: 5, color: "#FFB03A " },
        { id: 6, color: "#FFEB3A" },
        { id: 7, color: "#4383FF" },
        { id: 8, color: "#FF1A27" },
        { id: 9, color: "#048A02" },
        { id: 10, color: "#5AB0FF" },
        { id: 1, color: "#FFFFFF" },
        { id: 2, color: "#747474" },
        { id: 3, color: "#232323" },
        { id: 4, color: "#351B7D" },
        { id: 5, color: "#FFB03A " },
        { id: 6, color: "#FFEB3A" },
        { id: 7, color: "#4383FF" },
        { id: 8, color: "#FF1A27" },
        { id: 9, color: "#048A02" },
        { id: 10, color: "#5AB0FF" },
        { id: 1, color: "#FFFFFF" },
        { id: 2, color: "#747474" },
        { id: 3, color: "#232323" },
        { id: 4, color: "#351B7D" },
        { id: 5, color: "#FFB03A " },
        { id: 6, color: "#FFEB3A" },
        { id: 7, color: "#4383FF" },
        { id: 8, color: "#FF1A27" },
        { id: 9, color: "#048A02" },
        { id: 10, color: "#5AB0FF" },
        { id: 1, color: "#FFFFFF" },
        { id: 2, color: "#747474" },
        { id: 3, color: "#232323" },
        { id: 4, color: "#351B7D" },
        { id: 5, color: "#FFB03A " },
        { id: 6, color: "#FFEB3A" },
        { id: 7, color: "#4383FF" },
        { id: 8, color: "#FF1A27" },
        { id: 9, color: "#048A02" },
        { id: 10, color: "#5AB0FF" },
      ],
      setFurnitureItems: {
        ["pixelhouse"]: {
          label: "House",
          items: [
            { model: "qua_0r_house_floor", price: 1, label: "Floor #1" },
            { model: "qua_0r_house_floor_2", price: 1, label: "Floor #2" },
            { model: "qua_0r_house_floor_3", price: 1, label: "Floor #3" },
            { model: "qua_0r_house_floor_4", price: 1, label: "Floor #4" },
            { model: "qua_0r_house_floor_5", price: 1, label: "Floor #5" },
            { model: "qua_0r_house_floor_6", price: 1, label: "Floor #6" },
            {
              model: "qua_0r_house_circlefloor",
              price: 1,
              label: "Floor (Circle)",
            },
            { model: "qua_0r_house_doorwall", price: 1, label: "Door Wall" },
            { model: "qua_0r_house_wall", price: 1, label: "Wall" },
            { model: "qua_0r_house_wall_2", price: 1, label: "Wall #2" },
            { model: "qua_0r_house_wall_3", price: 1, label: "Wall #3" },
            {
              model: "qua_0r_house_longwall",
              price: 1,
              label: "Wall (Long)",
            },
            {
              model: "qua_0r_house_longwall_2",
              price: 1,
              label: "Wall (Long) #2",
            },
            {
              model: "qua_0r_house_tallwall",
              price: 1,
              label: "Wall (Long) #3",
            },
            {
              model: "qua_0r_house_stair_extra",
              price: 1,
              label: "Stair (Extra)",
            },
          ],
        },
      },
    } as any,
  },
  {
    action: "ui:setInHouse",
    data: {
      owner: true,
      type: "square",
      owner_name: "Ali Koç",
      houseId: 1,
      authorized: true,
      guest: false,
      indicators: {
        electricity: 320,
        water: 240,
        power: 400,
        gas: 750,
      },
      permissions: [
        {
          playerName: "Selin Korkmaz",
          user: "A1",
        },
      ],
      options: {
        lights: false,
        tint: 1,
        stairs: false,
        rooms: false,
      },
      furnitures: [
        {
          index: 1,
          isPlaced: true,
          label: "Test #1",
          model: "",
          objectId: 1,
          price: 1,
        },
        {
          index: 1,
          isPlaced: false,
          label: "Test #2",
          model: "",
          objectId: 1,
          price: 1,
        },
        {
          index: 1,
          isPlaced: true,
          label: "Test #3",
          model: "",
          objectId: 1,
          price: 1,
        },
      ],
      created_at: "",
    } as InHouseTypes,
  },
]);
