--[[ Configuration settings ]]
Config = {}

--[[ Locale setting for language localization. ]]
Config.Locale             = "en"

---@type EventName | nil -- Cloth menu event name for house wardrobe
Config.ClothMenuEventName = nil

--[[ If qb-inventory is used and the version is higher than 2.0.0 then enable this setting, otherwise set value to 'false' ]]
Config.NewInventoryQB = false

--[[ MetaKeys | Only ESX | if your esx version is old or you get a "setMeta" error. Set value to false. ]]
Config.MetaKeys = true

--[[ Commands ]]
Config.Commands = {
    -- Main command,the menu wheree verything is managed.
    useMainPanel = "pixelhouse",
    -- Create new house | Only admin.
    useCreateHouse = "createpixelhouse",
    -- Let the player who rings the bell into the house
    useAnswerDoorBell = "checkdoor",
}

--[[ Open Panel With Tablet Item ]]
Config.OpenPanelWithTablet = {
    active = true,
    itemName = "tablethouse",
}

--[[ Add blips to houses for sale. ]]
Config.SaleHouseBlip = {
    active = true,
    sprite = 350,
    color = 2,
    scale = 0.7,
}

--[[ Add blips to purchased houses. If the other home blip is open, it updates with it. ]]
Config.HouseOwnedBlip = {
    active = true,
    sprite = 40,
    color = 3,
    scale = 0.7,
}

--[[ Players can only buy 1 house, If false there is no limit ! ]]
Config.MaxHouseLimitPerPlayer = 5

--[[ Stairs can be placed or removed. ]]
Config.EditableStairs = true

--[[ Place/Rooms can be placed or removed. ]]
Config.EditableRooms = true

--[[ Furniture-based stash ]]
Config.StashOptions = {
    active = true,
    slots = 50,
    maxWeight = 1000000000,
}

--[[ Real-Estate ]]
--[[ Use Commands.useCreateHouse Command. Players can create a house. They cannot do anything else. It is not a detailed system. ]]
Config.RealEstate = {
    enable = true,
    jobs = {
        ["realestate"] = true,
    },
}

--[[ Furniture-based wardrobe ]]
Config.WardrobeOptions = {
    active = true,
}

--[[ Raid ]]
Config.Raid = {
    enable = true,         -- Enable/Disable raiding
    canUseStash = true,     -- Can access stashes.
    itemRequired = {        -- Item required to raid
        removeItem = true,  -- Remove item from inventory
        name = "lockpick",  -- Item name
        label = "LockPick", -- Item label
        itemCount = 1,      -- Item count
    },
}

Config.InteriorHouseTypes = {
    ["square"] = {
        label = "square",
        door_coords = vec3(-1452.1873, -540.6914, 74.0443),
        enter_coords = vec4(-1452.1873, -540.6914, 74.0443, 41.6835),
        max_stash_count = 10,
    },
    ["rectangle"] = {
        label = "Rectangle",
        door_coords = vec3(402.9340, -1263.9220, -84.0736),
        enter_coords = vec4(402.8653, -1265.3367, -84.0736, 176.2434),
        max_stash_count = 10,
    },
    ["furnished"] = {
        label = "Furnished",
        door_coords = vec3(93.6972, -485.8475, -109.0118),
        enter_coords = vec4(92.1094, -485.8838, -109.0118, 91.5934),
        max_stash_count = 10,
    },
    ["apa_v_mp_h"] = {
        label = "Apa V MP",
        door_coords = vec3(-782.2, 319, 187.9),
        enter_coords = vec3(-782.2, 319, 187.9),
        max_stash_count = 10,
    },
}

--[[ InteriorHouseGarage]]
Config.InteriorHouseGarage = {
    coords = {
        enter = vec3(520.00000000, -2625.00000000, -39.69168000),
        exit = vec3(519.9845, -2637.2595, -38.6916),
        vehicles = {
            vec4(514.0, -2612.69, -38.5, 273.83),
            vec4(514.0, -2616.69, -38.5, 273.83),
            vec4(514.0, -2620.69, -38.5, 273.83),
            vec4(514.0, -2624.69, -38.5, 273.83),
            vec4(514.0, -2628.69, -38.5, 273.83),
            vec4(514.0, -2632.69, -38.5, 273.83),
            vec4(525.46, -2612.53, -38.5, 92.52),
            vec4(525.46, -2616.64, -38.5, 92.52),
            vec4(525.46, -2620.64, -38.5, 92.52),
            vec4(525.46, -2624.64, -38.5, 92.52),
            vec4(525.46, -2628.64, -38.5, 92.52),
            vec4(525.46, -2632.64, -38.5, 92.52),
        }
    }
}

--[[ Houses ]]
--[[ It will be added to the database automatically. You can add it from here or from the game. ]]
Config.Houses = {
    [1] = {
        houseId = 1,
        label = "House",
        price = 100000,
        door_coords = vector4(-830.8799, 115.0645, 55.2, 273.3748),
        garage_coords = vector4(-835.1329, 117.6848, 54.75, 24.3042),
        coords_label = "Portola Drive, Rockford Hills",
    },
    [2] = {
        houseId = 2,
        label = "House",
        price = 100000,
        door_coords = vector4(997.1400, -729.3287, 57.15, 312.5908),
        garage_coords = vector4(1005.2209, -733.4166, 56.8, 311.1407),
        coords_label = "West Mirror Drive",
    },
    [3] = {
        houseId = 3,
        label = "House",
        price = 100000,
        door_coords = vector4(979.2260, -716.1286, 57.5, 312.9578),
        garage_coords = vector4(977.4029, -712.7181, 57.1, 314.8710),
        coords_label = "West Mirror Drive",
    },
    [4] = {
        houseId = 4,
        label = "House",
        price = 100000,
        door_coords = vector4(970.7920, -701.3616, 57.5, 347.3936),
        garage_coords = vector4(971.6374, -686.5910, 57.15, 315.32),
        coords_label = "West Mirror Drive",
    },
    [5] = {
        houseId = 5,
        label = "House",
        price = 100000,
        door_coords = vector4(943.3665, -653.4132, 57.8, 239.1503),
        garage_coords = vector4(947.4243, -656.6040, 57.35, 307.4706),
        coords_label = "West Mirror Drive",
    },
    [6] = {
        houseId = 6,
        label = "House",
        price = 100000,
        door_coords = vector4(928.8663, -639.7185, 57.5, 309.2115),
        garage_coords = vector4(914.2787, -643.4884, 57.2, 322.1532),
        coords_label = "West Mirror Drive",
    },
    [7] = {
        houseId = 7,
        label = "House",
        price = 100000,
        door_coords = vector4(903.4822, -615.5178, 57.8, 257.7338),
        garage_coords = vector4(913.6213, -629.6578, 57.35, 318.9046),
        coords_label = "West Mirror Drive",
    },
    [8] = {
        houseId = 8,
        label = "House",
        price = 100000,
        door_coords = vector4(886.7679, -608.2051, 57.8, 315.7554),
        garage_coords = vector4(871.6521, -601.5024, 57.6, 314.2954),
        coords_label = "West Mirror Drive",
    },
    [9] = {
        houseId = 9,
        label = "House",
        price = 100000,
        door_coords = vector4(844.1382, -562.7495, 57.3, 202.1745),
        garage_coords = vector4(843.6161, -567.0984, 57.1, 277.7262),
        coords_label = "West Mirror Drive",
    },
    [10] = {
        houseId = 10,
        label = "House",
        price = 100000,
        door_coords = vector4(944.4925, -463.2038, 60.9, 116.8149),
        garage_coords = vector4(940.0060, -464.7273, 60.6, 209.2318),
        coords_label = "West Mirror Drive",
    },
    [11] = {
        houseId = 11,
        label = "House",
        price = 100000,
        door_coords = vector4(987.5931, -433.0792, 63.3, 215.2337),
        garage_coords = vector4(988.7687, -437.3375, 63.1, 300.9896),
        coords_label = "West Mirror Drive",
    },
    [12] = {
        houseId = 12,
        label = "House",
        price = 100000,
        door_coords = vector4(945.9721, -518.7975, 60.0, 271.2817),
        garage_coords = vector4(949.2786, -514.9356, 59.0, 12.0338),
        coords_label = "West Mirror Drive",
    },
}

--[[ House Indicators ]]
Config.Indicators = {
    electricity = {
        unitPrice = 5, -- [[ Unit price at the time of purchase ]]
        maxValue = 1000 --[[ Max value that can be stored ]]
    },
    power = {
        unitPrice = 5,
        maxValue = 1000
    },
    gas = {
        unitPrice = 5,
        maxValue = 1000
    },
    water = {
        unitPrice = 5,
        maxValue = 1000
    },
}

--[[ CCTV ]]
Config.CCTV = {
    Enabled = true,
    MaxZoom = 30,
    MinZoom = 100,
    RotateSpeed = 0.3,
    Controls = {
        ZoomIn = 96,  -- UP Arrow
        ZoomOut = 97, -- DOWN Arrow
        Exit = 194,   -- BACKSPACE
    }
}

--[[ House Wall Colors ]]
Config.WallColors = {
    { id = 1,  color = "#FFDB28" },
    { id = 2,  color = "#FF6F00" },
    { id = 3,  color = "#BF1F19" },
    { id = 4,  color = "#FF2525" },
    { id = 5,  color = "#f5f5dc " },
    { id = 7,  color = "#DDDAD7" },
    { id = 9,  color = "#666666" },
    { id = 13, color = "#0a0403" },
    { id = 15, color = "#AE6E1E" },
    { id = 19, color = "#6d3300" },
    { id = 22, color = "#99821E" },
    { id = 23, color = "#83961E" },
    { id = 24, color = "#6CAA1E" },
    { id = 25, color = "#57BD1E" },
    { id = 26, color = "#00bf5f" },
    { id = 30, color = "#265816" },
    { id = 31, color = "#00C1A7" },
    { id = 33, color = "#40D0BD" },
    { id = 34, color = "#00B5B8" },
    { id = 36, color = "#0494E4" },
    { id = 37, color = "#7338FF" },
    { id = 39, color = "#8131FF" },
    { id = 40, color = "#bf005f" },
    { id = 1,  color = "#FFDB28" },
    { id = 2,  color = "#FF6F00" },
    { id = 3,  color = "#BF1F19" },
    { id = 4,  color = "#FF2525" },
    { id = 5,  color = "#f5f5dc " },
    { id = 7,  color = "#DDDAD7" },
    { id = 9,  color = "#666666" },
    { id = 13, color = "#0a0403" },
    { id = 15, color = "#AE6E1E" },
    { id = 19, color = "#6d3300" },
    { id = 22, color = "#99821E" },
    { id = 23, color = "#83961E" },
    { id = 24, color = "#6CAA1E" },
    { id = 25, color = "#57BD1E" },
    { id = 26, color = "#00bf5f" },
    { id = 30, color = "#265816" },
    { id = 33, color = "#40D0BD" },
    { id = 31, color = "#00C1A7" },
    { id = 33, color = "#40D0BD" },
    { id = 34, color = "#00B5B8" },
    { id = 36, color = "#0494E4" },
    { id = 37, color = "#7338FF" },
    { id = 39, color = "#8131FF" },
    { id = 40, color = "#bf005f" },
    { id = 41, color = "#FF8096" },
}

--[[ Furniture Items ]]
Config.FurnitureItems = {
    --[[["pixelhouse"] = {
        label = "House",
        items = {
            { model = "qua_0r_house_floor",       price = 1000, label = "Floor #1" },
            { model = "qua_0r_house_floor_2",     price = 1000, label = "Floor #2" },
            { model = "qua_0r_house_floor_3",     price = 1000, label = "Floor #3" },
            { model = "qua_0r_house_floor_4",     price = 1000, label = "Floor #4" },
            { model = "qua_0r_house_floor_5",     price = 1000, label = "Floor #5" },
            { model = "qua_0r_house_floor_6",     price = 1000, label = "Floor #6" },
            { model = "qua_0r_house_circlefloor", price = 1000, label = "Floor (Circle)" },
            { model = "qua_0r_house_doorwall",    price = 1000, label = "Door Wall" },
            { model = "qua_0r_house_wall",        price = 1000, label = "Wall" },
            { model = "qua_0r_house_wall_2",      price = 1000, label = "Wall #2" },
            { model = "qua_0r_house_wall_3",      price = 1000, label = "Wall #3" },
            { model = "qua_0r_house_longwall",    price = 1000, label = "Wall (Long)" },
            { model = "qua_0r_house_longwall_2",  price = 1000, label = "Wall (Long) #2" },
            { model = "qua_0r_house_tallwall",    price = 1000, label = "Wall (Long) #3" },
            -- { model = "qua_0r_house_stair_extra", price = 1000, label = "Stair (Extra)" },
        },
    },]]
    ["stashes"] = {
    label = "Tárolók",
    items = {
        [1] = { model = "v_res_tre_storagebox", price = 2500, label = "Tárolódoboz" },
        [2] = { model = "prop_devin_box_closed", price = 2500, label = "Devin Doboz" },
        [3] = { model = "prop_mil_crate_01", price = 2500, label = "Katonai Láda 1" },
        [4] = { model = "prop_mil_crate_02", price = 2500, label = "Katonai Láda 2" },
        [5] = { model = "prop_box_wood05a", price = 2500, label = "Fa Doboz 5" },
        [6] = { model = "prop_drop_crate_01", price = 2500, label = "Leejtett Láda 1" },
        [7] = { model = "prop_box_wood02a_pu", price = 2500, label = "Fa Doboz 2 PU" },
        [8] = { model = "prop_box_wood04a", price = 2500, label = "Fa Doboz 4" },
        [9] = { model = "prop_crate_07a", price = 2500, label = "Láda 7" },
        [10] = { model = "prop_mb_crate_01a", price = 2500, label = "Láda 1" },
    },
},
["wardrobe"] = {
    label = "Ruhásszekrény",
    items = {
        [1] = { model = "v_res_tre_wardrobe", price = 2500, label = "V Ruhásszekrény" },
    },
},

    --[[["weed_planter"] = {
        label = "Weed Planter",
        items = {
            { model = "qua_weed_planter",       price = 2000, label = "Weed Planter" },
            { model = "qua_weed_planter_basic", price = 1000, label = "Weed Planter Basic" },
        }
    },
    ["weed_dryer"] = {
        label = "Weed Dryer",
        items = {
            { model = "qua_weed_dryer", price = 1000, label = "Weed Dryer" },
        }
    },
    ["weed_heather"] = {
        label = "Weed Heather",
        items = {
            { model = "qua_weed_heather",     price = 1000, label = "Weed Heather #1" },
            { model = "prop_elec_heater_01",  price = 1000, label = "Weed Heather #2" },
            { model = "prop_patio_heater_01", price = 1000, label = "Weed Heather #3" },
        }
    },
    ["weed_light"] = {
        label = "Weed Light",
        items = {
            { model = "prop_wall_light_05a",              price = 1000, label = "Wall Light" },
            { model = "ch_prop_ch_lamp_ceiling_w_01a",    price = 1000, label = "Lamp Ceiling" },
            { model = "h4_prop_x17_sub_lampa_small_blue", price = 1000, label = "Lamp Small Blue" },
        }
    },
    ["weed_fans"] = {
        label = "Weed Fans",
        items = {
            { model = "prop_fan_01",       price = 1000, label = "Fan 01" },
            { model = "v_res_fa_fan",      price = 1000, label = "Fa Fan" },
            { model = "prop_wall_vent_02", price = 1000, label = "Fan Went" },
        }
    },
    ["weed_table"] = {
        label = "Weed Table",
        items = {
            { model = "bkr_prop_weed_table_01a", price = 1000, label = "Table" },
        }
    },]]
    ["sofas"] = {
    label = "Kanapék",
    items = {
        { model = "miss_rub_couch_01",           price = 300,  label = "Régi kanapé" },
        { model = "prop_fib_3b_bench",           price = 700,  label = "Háromszemélyes kanapé" },
        { model = "prop_ld_farm_chair01",        price = 250,  label = "Régi szék" },
        { model = "prop_ld_farm_couch01",        price = 300,  label = "Régi háromszemélyes kanapé" },
        { model = "prop_ld_farm_couch02",        price = 300,  label = "Régi csíkos kanapé" },
        { model = "v_res_d_armchair",            price = 300,  label = "Sárga fotel" },
        { model = "v_res_fh_sofa",               price = 3700, label = "Sarokkanapé" },
        { model = "v_res_mp_sofa",               price = 3700, label = "Sarokkanapé 2" },
        { model = "v_res_d_sofa",                price = 700,  label = "Kanapé 1" },
        { model = "v_res_j_sofa",                price = 700,  label = "Kanapé 2" },
        { model = "v_res_mp_stripchair",         price = 700,  label = "Kanapé 3" },
        { model = "v_res_m_h_sofa_sml",          price = 700,  label = "Kanapé 4" },
        { model = "v_res_r_sofa",                price = 700,  label = "Kanapé 5" },
        { model = "v_res_tre_sofa",              price = 700,  label = "Kanapé 6" },
        { model = "v_res_tre_sofa_mess_a",       price = 700,  label = "Koszos kanapé A" },
        { model = "v_res_tre_sofa_mess_b",       price = 700,  label = "Koszos kanapé B" },
        { model = "v_res_tre_sofa_mess_c",       price = 700,  label = "Koszos kanapé C" },
        { model = "v_res_tt_sofa",               price = 700,  label = "Kanapé 10" },
        { model = "prop_rub_couch02",            price = 700,  label = "Rongyos kanapé" },
        { model = "v_ilev_m_sofa",               price = 2000, label = "Fehér kanapé" },
        { model = "v_med_p_sofa",                price = 1000, label = "Barna bőrkanapé" },
        { model = "v_club_officesofa",           price = 500,  label = "Piros kanapé" },
        { model = "bkr_prop_clubhouse_sofa_01a", price = 1000, label = "Fekete kanapé" },
        { model = "apa_mp_h_stn_sofacorn_01",    price = 5000, label = "Sarokkanapé 3" },
        { model = "prop_couch_lg_02",            price = 1000, label = "Nagy kanapé" },
        { model = "apa_mp_h_stn_sofacorn_10",    price = 5000, label = "Sarokkanapé 4" },
        { model = "apa_mp_h_yacht_sofa_02",      price = 1000, label = "Barna yacht kanapé" },
        { model = "apa_mp_h_yacht_sofa_01",      price = 5000, label = "Hosszú fehér kanapé" },
        { model = "prop_couch_01",               price = 1000, label = "Párnázott kanapé" },
        { model = "prop_couch_03",               price = 1000, label = "Sárga kanapé" },
        { model = "prop_couch_04",               price = 1000, label = "Bőr kanapé párnákkal" },
        { model = "prop_couch_lg_05",            price = 500,  label = "Kordbársony kanapé" },
        { model = "prop_couch_lg_06",            price = 1000, label = "Barna bőrkanapé 2" },
        { model = "prop_couch_lg_07",            price = 1000, label = "Párnázott kanapé 2" },
        { model = "prop_couch_lg_08",            price = 1000, label = "Barna bőrkanapé 3" },
        { model = "prop_couch_sm1_07",           price = 500,  label = "Sarok bőrkanapé" },
        { model = "prop_couch_sm2_07",           price = 500,  label = "Egyenes bőrkanapé" },
        { model = "prop_couch_sm_06",            price = 500,  label = "Kis bőrkanapé" },
        { model = "apa_mp_h_stn_sofa2seat_02",   price = 1000, label = "Kétszemélyes kanapé" },
        { model = "apa_mp_h_stn_sofacorn_05",    price = 5000, label = "Sarokkanapé 5" },
        { model = "apa_mp_h_stn_sofacorn_06",    price = 5000, label = "Sarokkanapé 6" },
        { model = "apa_mp_h_stn_sofacorn_07",    price = 5000, label = "Sarokkanapé 7" },
        { model = "apa_mp_h_stn_sofacorn_08",    price = 5000, label = "Sarokkanapé 8" },
        { model = "apa_mp_h_stn_sofacorn_09",    price = 5000, label = "Sarokkanapé 9" },
        { model = "ex_mp_h_off_sofa_003",        price = 1000, label = "Kék szövetkanapé" },
        { model = "ex_mp_h_off_sofa_01",         price = 1000, label = "Fehér bőrkanapé" },
        { model = "ex_mp_h_off_sofa_02",         price = 1000, label = "Fekete bőrkanapé" },
        { model = "hei_heist_stn_sofa2seat_03",  price = 1000, label = "Modern kanapé" },
        { model = "hei_heist_stn_sofa2seat_06",  price = 1000, label = "Barna kanapé" },
        { model = "hei_heist_stn_sofa3seat_01",  price = 1000, label = "Fekvőfotel" },
        { model = "hei_heist_stn_sofa3seat_02",  price = 1000, label = "Modern kanapé 2" },
        { model = "hei_heist_stn_sofa3seat_06",  price = 1000, label = "Modern kanapé 3" },
        { model = "imp_prop_impexp_sofabed_01a", price = 1000, label = "Kanapéágy" },
        { model = "prop_t_sofa_02",              price = 1000, label = "Kanapéágy 2" }
    },
},
["chairs"] = {
    label = "Székek",
    items = {
        { model = "v_res_m_dinechair",           price = 300,  label = "Étkezőszék 1" },
        { model = "v_res_m_armchair",            price = 300,  label = "Karosszék" },
        { model = "v_res_jarmchair",             price = 300,  label = "Bőr fotel" },
        { model = "v_res_fh_dineeamesa",         price = 300,  label = "Étkezőszék 2" },
        { model = "v_res_fa_chair01",            price = 300,  label = "Fa szék" },
        { model = "v_res_d_highchair",           price = 300,  label = "Magas szék" },
        { model = "v_res_d_bedsidechair",        price = 300,  label = "Ágy melletti szék" },
        { model = "v_res_d_armchair",            price = 300,  label = "Sárga fotel" },
        { model = "v_res_carmchair",             price = 300,  label = "Textil fotel" },
        { model = "v_res_tre_chair",             price = 300,  label = "Régi fa szék" },
        { model = "v_res_tre_officechair",       price = 300,  label = "Irodai szék 1" },
        { model = "v_res_tre_stool",             price = 100,  label = "Sámli" },
        { model = "v_res_tre_stool_leather",     price = 100,  label = "Bőr sámli" },
        { model = "v_res_m_chair",               price = 300,  label = "Étkezőszék 3" },
        { model = "v_res_mp_highchair",          price = 300,  label = "Magas étkezőszék" },
        { model = "v_res_mp_stripchair",         price = 300,  label = "Élénk színű szék" },
        { model = "v_res_mp_r_marmchair",        price = 300,  label = "Modern karosszék" },
        { model = "v_res_fh_easychair",          price = 300,  label = "Kényelmes fotel" },
        { model = "v_res_fh_bench",              price = 500,  label = "Fapad" },
        { model = "prop_direct_chair_01",        price = 500,  label = "Rendezői szék" },
        { model = "prop_yacht_seat_01",          price = 400,  label = "Yacht szék" },
        { model = "prop_yacht_seat_02",          price = 400,  label = "Yacht szék 2" },
        { model = "prop_yacht_seat_03",          price = 400,  label = "Yacht szék 3" },
        { model = "prop_cs_office_chair",        price = 400,  label = "Forgószék" },
        { model = "prop_chair_01a",              price = 300,  label = "Kerti szék 1" },
        { model = "prop_chair_02",               price = 300,  label = "Kerti szék 2" },
        { model = "prop_chair_03",               price = 300,  label = "Kerti szék 3" },
        { model = "prop_chair_04a",              price = 300,  label = "Konyhai szék" },
        { model = "prop_chair_05",               price = 300,  label = "Régi fa szék" },
        { model = "prop_chair_06",               price = 300,  label = "Kültéri műanyag szék" },
        { model = "prop_chair_07",               price = 300,  label = "Összecsukható szék" },
        { model = "prop_chair_08",               price = 300,  label = "Műanyag szék" },
        { model = "prop_chair_09",               price = 300,  label = "Régi szék párnával" },
        { model = "prop_chair_10",               price = 300,  label = "Étkezőszék 4" },
        { model = "prop_chair_pile_01",          price = 500,  label = "Székhalom" },
        { model = "prop_off_chair_01",           price = 400,  label = "Irodai szék 2" },
        { model = "prop_off_chair_03",           price = 400,  label = "Bőr irodai szék" },
        { model = "prop_off_chair_04",           price = 400,  label = "Fekete irodai szék" },
        { model = "prop_off_chair_04b",          price = 400,  label = "Forgószék párnával" },
        { model = "prop_off_chair_05",           price = 400,  label = "Régi irodai szék" },
        { model = "prop_table_03b_chr",          price = 250,  label = "Étkezőszék 5" },
        { model = "prop_table_04_chr",           price = 250,  label = "Étkezőszék 6" },
        { model = "v_ilev_leath_chr",            price = 300,  label = "Bőr étkezőszék" },
        { model = "v_ilev_armchair",             price = 300,  label = "Karosszék 2" },
        { model = "hei_prop_yah_seat_01",        price = 400,  label = "Modern yacht szék" },
        { model = "hei_prop_yah_seat_02",        price = 400,  label = "Modern yacht szék 2" },
        { model = "hei_prop_yah_seat_03",        price = 400,  label = "Modern yacht szék 3" },
        { model = "ex_office_chairexec",         price = 600,  label = "Főnöki szék" },
        { model = "ex_office_chair001",          price = 600,  label = "Modern irodai szék" },
        { model = "ex_office_chair02",           price = 600,  label = "Design szék" },
        { model = "ba_prop_club_chair_01",       price = 400,  label = "Klubszék" },
        { model = "apa_mp_h_stn_chairarm_11",    price = 400,  label = "Modern karosszék" },
        { model = "apa_mp_h_stn_chairarm_23",    price = 400,  label = "Modern szék 2" },
        { model = "apa_mp_h_stn_chairarm_24",    price = 400,  label = "Modern szék 3" },
        { model = "apa_mp_h_stn_chairstrip_01",  price = 400,  label = "Elegáns szék" },
        { model = "apa_mp_h_stn_chairstrip_05",  price = 400,  label = "Elegáns szék 2" }
    },
},

["beds"] = {
    label = "Ágyak",
    items = {
        { model = "v_res_d_bed",                price = 700,  label = "Ágy 1" },
        { model = "v_res_lestersbed",           price = 700,  label = "Ágy 2" },
        { model = "v_res_mbbed",                price = 700,  label = "MB ágy" },
        { model = "v_res_mdbed",                price = 700,  label = "MD ágy" },
        { model = "v_res_msonbed",              price = 700,  label = "Ágy 3" },
        { model = "v_res_tre_bed1",             price = 700,  label = "Ágy 4" },
        { model = "v_res_tre_bed2",             price = 700,  label = "T ágy" },
        { model = "v_res_tt_bed",               price = 700,  label = "TT ágy" },
        { model = "apa_mp_h_bed_with_table_02", price = 5000, label = "Elegáns ágy" },
        { model = "apa_mp_h_bed_wide_05",       price = 5000, label = "Piros ágy" },
        { model = "apa_mp_h_bed_double_08",     price = 3000, label = "Szögletes ágy" },
        { model = "apa_mp_h_bed_double_09",     price = 3000, label = "Modern ágy" },
        { model = "apa_mp_h_yacht_bed_01",      price = 5000, label = "California king" },
        { model = "apa_mp_h_yacht_bed_02",      price = 5000, label = "California king 2" },
        { model = "bkr_prop_biker_campbed_01",  price = 100,  label = "Tábori ágy" },
        { model = "ex_prop_exec_bed_01",        price = 700,  label = "Kis ágy" },
        { model = "gr_prop_bunker_bed_01",      price = 700,  label = "Kis ágy 2" },
        { model = "p_mbbed_s",                  price = 700,  label = "Ágy 5" }
    },
},
["general"] = {
    label = "Általános",
    items = {
        { model = "v_corp_facebeanbag",       price = 100,  label = "Babzsák 1" },
        { model = "v_res_cherubvase",         price = 2500, label = "Fehér váza" },
        { model = "v_res_d_paddedwall",       price = 300,  label = "Párnázott fal" },
        { model = "v_res_d_ramskull",         price = 300,  label = "Koponya" },
        { model = "v_res_d_whips",            price = 300,  label = "Ostorok" },
        { model = "v_res_fashmag1",           price = 300,  label = "Magazinok" },
        { model = "v_res_fashmagopen",        price = 300,  label = "Nyitott magazinok" },
        { model = "v_res_fa_magtidy",         price = 300,  label = "Rendezett magazinok" },
        { model = "v_res_fa_yogamat002",      price = 300,  label = "Jógamatrac 1" },
        { model = "v_res_fa_yogamat1",        price = 300,  label = "Jógamatrac 2" },
        { model = "v_res_fh_aftershavebox",   price = 300,  label = "Borotválkozókészlet" },
        { model = "v_res_fh_flowersa",        price = 300,  label = "Virágok" },
        { model = "v_res_fh_fruitbowl",       price = 300,  label = "Gyümölcstál" },
        { model = "v_res_fh_laundrybasket",   price = 300,  label = "Szennyestartó" },
        { model = "v_res_fh_pouf",            price = 300,  label = "Puff" },
        { model = "v_res_fh_sculptmod",       price = 300,  label = "Szobor" },
        { model = "v_res_j_magrack",          price = 300,  label = "Újságtartó" },
        { model = "v_res_jewelbox",           price = 300,  label = "Ékszerdoboz" },
        { model = "v_res_mbbin",              price = 300,  label = "Szemetes" },
        { model = "v_res_mbowlornate",        price = 300,  label = "Dísztál" },
        { model = "v_res_mbronzvase",         price = 300,  label = "Bronz váza" },
        { model = "v_res_mchalkbrd",          price = 300,  label = "Táblára író tábla" },
        { model = "v_res_mddresser",          price = 300,  label = "Fiókos szekrény" },
        { model = "v_res_mplinth",            price = 300,  label = "Talapzat" },
        { model = "v_res_mp_ashtrayb",        price = 300,  label = "Hamutál" },
        { model = "v_res_m_candle",           price = 300,  label = "Gyertya" },
        { model = "v_res_m_candlelrg",        price = 300,  label = "Nagy gyertya" },
        { model = "v_res_m_kscales",          price = 300,  label = "Mérleg" },
        { model = "v_res_tt_bedpillow",       price = 300,  label = "Párna" },
        { model = "v_med_cor_whiteboard",     price = 300,  label = "Fehértábla" },
        { model = "prop_ashtray_01",          price = 100,  label = "Fekete hamutál" },
        { model = "v_ret_fh_ashtray",         price = 100,  label = "Kő hamutál" },
        { model = "v_24_wdr_mesh_rugs",       price = 500,  label = "Szőnyeg" },
        { model = "apa_mp_h_acc_rugwooll_04", price = 500,  label = "Szőnyeg 2" },
        { model = "ex_mp_h_acc_rugwoolm_04",  price = 500,  label = "Szőnyeg 3" },
        { model = "apa_mp_h_acc_rugwoolm_03", price = 500,  label = "Szőnyeg 4" },
        { model = "apa_mp_h_acc_rugwooll_03", price = 500,  label = "Szőnyeg 5" },
        { model = "apa_mp_h_acc_rugwoolm_04", price = 500,  label = "Szőnyeg 6" },
        { model = "v_club_rack",              price = 500,  label = "Ruhatartó állvány" }
    },
},

    ["general2"] = {
        label = "Tárgyak",
    items = {
        { model = "prop_a4_pile_01",               price = 100, label = "A4 papírkupac" },
        { model = "prop_amb_40oz_03",              price = 100, label = "40 uncia" },
        { model = "prop_amb_beer_bottle",          price = 100, label = "Sör" },
        { model = "prop_aviators_01",              price = 100, label = "Aviátor napszemüveg" },
        { model = "prop_barry_table_detail",       price = 100, label = "Asztaldísz" },
        { model = "prop_beer_box_01",              price = 100, label = "Sörösdoboz" },
        { model = "prop_binoc_01",                 price = 100, label = "Távcső" },
        { model = "prop_blox_spray",               price = 100, label = "Festékszóró" },
        { model = "prop_bongos_01",                price = 100, label = "Bongók" },
        { model = "prop_bong_01",                  price = 100, label = "Vízipipa" },
        { model = "prop_boombox_01",               price = 100, label = "Boombox" },
        { model = "prop_bowl_crisps",              price = 100, label = "Ropogós tál" },
        { model = "prop_candy_pqs",                price = 100, label = "Cukorka" },
        { model = "prop_carrier_bag_01",           price = 100, label = "Bevásárlótáska" },
        { model = "prop_ceramic_jug_01",           price = 100, label = "Kerámia kancsó" },
        { model = "prop_cigar_pack_01",            price = 100, label = "Szivar csomag 1" },
        { model = "prop_cigar_pack_02",            price = 100, label = "Szivar csomag 2" },
        { model = "prop_cs_beer_box",              price = 100, label = "Sörösdoboz 2" },
        { model = "prop_cs_binder_01",             price = 100, label = "Irattartó" },
        { model = "prop_cs_bs_cup",                price = 100, label = "Pohár" },
        { model = "prop_cs_cashenvelope",          price = 100, label = "Boros boríték" },
        { model = "prop_cs_champ_flute",           price = 100, label = "Pezsgőspohár" },
        { model = "prop_cs_duffel_01",             price = 100, label = "Sporttáska" },
        { model = "prop_cs_dvd",                   price = 50,  label = "DVD" },
        { model = "prop_cs_dvd_case",              price = 50,  label = "DVD tok" },
        { model = "prop_cs_film_reel_01",          price = 100, label = "Filmgörgő" },
        { model = "prop_cs_ilev_blind_01",         price = 100, label = "Reluxa" },
        { model = "p_ld_bs_bag_01",                price = 100, label = "Táska" },
        { model = "prop_cs_ironing_board",         price = 100, label = "Vasalódeszka" },
        { model = "prop_cs_katana_01",             price = 100, label = "Katana" },
        { model = "prop_cs_kettle_01",             price = 100, label = "Vízforraló" },
        { model = "prop_cs_lester_crate",          price = 100, label = "Láda" },
        { model = "prop_cs_petrol_can",            price = 100, label = "Benzinkanna" },
        { model = "prop_cs_sack_01",               price = 100, label = "Zsák" },
        { model = "prop_cs_script_bottle_01",      price = 100, label = "Gyógyszeres üveg" },
        { model = "prop_cs_script_bottle",         price = 100, label = "Gyógyszeres üveg 2" },
        { model = "prop_cs_street_binbag_01",      price = 100, label = "Szemeteszsák" },
        { model = "prop_cs_whiskey_bottle",        price = 100, label = "Whiskey üveg" },
        { model = "prop_sh_bong_01",               price = 100, label = "Vízipipa" },
        { model = "prop_peanut_bowl_01",           price = 100, label = "Mogyoró" },
        { model = "prop_tumbler_01",               price = 100, label = "Pohár" },
        { model = "prop_weed_bottle",              price = 100, label = "Fű üveg" },
        { model = "p_cs_lighter_01",               price = 100, label = "Öngyújtó" },
        { model = "p_cs_papers_01",                price = 100, label = "Cigis papírok" },
        { model = "v_res_d_dildo_f",               price = 100, label = "Fekete dildó" },
        { model = "v_res_d_dildo_c",               price = 100, label = "Fehér dildó" },
        { model = "v_res_d_dildo_a",               price = 100, label = "Anyuci játéka" },
        { model = "prop_champ_cool",               price = 100, label = "Pezsgőhűtő" },
        { model = "prop_champ_01b",                price = 100, label = "Pezsgősüveg" },
        { model = "prop_champ_flute",              price = 100, label = "Pezsgőspohár" },
        { model = "ba_prop_club_champset",         price = 300, label = "Pezsgőkészlet" },
        { model = "v_res_fa_candle01",             price = 100, label = "Kék gyertya" },
        { model = "v_res_fa_candle02",             price = 100, label = "Piros gyertya" },
        { model = "v_res_fa_candle03",             price = 100, label = "Fekete gyertya" },
        { model = "v_res_fa_candle04",             price = 100, label = "Kis gyertya" },
        { model = "v_med_bottles2",                price = 100, label = "Vegyszerek" },
        { model = "v_res_desktidy",                price = 100, label = "Irodai cuccok" },
        { model = "v_med_p_notebook",              price = 100, label = "Jegyzetfüzet" },
        { model = "bkr_prop_weed_dry_01a",         price = 100, label = "Fű hegy" },
        { model = "ba_prop_battle_trophy_battler", price = 100, label = "Ököl trófea" },
        { model = "ba_prop_battle_trophy_no1",     price = 100, label = "Csillag trófea" },
        { model = "prop_golf_bag_01c",             price = 100, label = "Golfzsák" },
        { model = "hei_heist_kit_bin_01",          price = 100, label = "Szemetes" },
        { model = "prop_wooden_barrel",            price = 100, label = "Fa hordó" },
        { model = "bkr_prop_bkr_cash_scatter_01",  price = 100, label = "Szétszórt pénz" },
        { model = "bkr_prop_bkr_cashpile_01",      price = 100, label = "Készpénz" },
        { model = "bkr_prop_bkr_cash_roll_01",     price = 100, label = "Pénztekercs" },
        { model = "bkr_prop_bkr_cashpile_04",      price = 100, label = "Pénzhalom" },
        { model = "bkr_prop_weed_bigbag_open_01a", price = 100, label = "Nyitott fűzsák" },
        { model = "bkr_prop_weed_bigbag_02a",      price = 100, label = "Fűzsák 2" },
        { model = "bkr_prop_weed_bigbag_03a",      price = 100, label = "Fűzsák 3" },
        { model = "bkr_prop_weed_scales_01a",      price = 100, label = "Mérleg" },
        { model = "bkr_prop_weed_smallbag_01a",    price = 100, label = "Kis zacskó" },
        { model = "prop_gold_bar",                 price = 100, label = "Aranyrúd" },
        { model = "beerrow_world",                 price = 100, label = "Sörösüvegek" },
        { model = "beerrow_local",                 price = 100, label = "Sörösüvegek 2" },
        { model = "p_cs_bbbat_01",                 price = 100, label = "Baseball ütő" },
        { model = "p_cs_cuffs_02_s",               price = 100, label = "Bilincs" },
        { model = "p_cs_joint_02",                 price = 100, label = "Joint" },
        { model = "p_ing_coffeecup_01",            price = 100, label = "Kávéscsésze" },
        { model = "p_tumbler_cs2_s",               price = 100, label = "Pohár" },
        { model = "prop_turkey_leg_01",            price = 100, label = "Csirkecomb" },
        { model = "prop_amb_donut",                price = 100, label = "Fánk" },
        { model = "prop_donut_02",                 price = 100, label = "Fánk 2" },
        { model = "prop_bar_shots",                price = 100, label = "Röviditalok" },
        { model = "prop_bar_stirrers",             price = 100, label = "Keverőpálcák" },
        { model = "prop_beer_amopen",              price = 100, label = "Felnyitott sör" },
        { model = "prop_beer_blr",                 price = 100, label = "Sör 1" },
        { model = "prop_beer_logger",              price = 100, label = "Sör 2" },
        { model = "prop_beer_stzopen",             price = 100, label = "Sör 3" },
        { model = "prop_bikerset",                 price = 100, label = "Motoros készlet" },
        { model = "prop_bottle_brandy",            price = 100, label = "Brandy üveg" },
        { model = "prop_tequila_bottle",           price = 100, label = "Tequila üveg" },
        { model = "prop_tequila",                  price = 100, label = "Tequila" },
        { model = "prop_bottle_cognac",            price = 100, label = "Konyakos üveg" },
        { model = "prop_bottle_macbeth",           price = 100, label = "Macbeth üveg" },
        { model = "prop_brandy_glass",             price = 100, label = "Brandy pohár" },
        { model = "prop_mug_01",                   price = 100, label = "Bögre 1" },
        { model = "prop_mug_02",                   price = 100, label = "Bögre 2" },
        { model = "prop_mug_03",                   price = 100, label = "Bögre 3" },
            { model = "prop_optic_vodka",              price = 100, label = "Vodka" },
{ model = "prop_optic_jd",                 price = 100, label = "Jack Daniels" },
{ model = "prop_pint_glass_01",            price = 100, label = "Pohár" },
{ model = "prop_pizza_box_03",             price = 100, label = "Pizzás doboz" },
{ model = "prop_sandwich_01",              price = 100, label = "Szendvics" },
{ model = "prop_cava",                     price = 100, label = "Pezsgő" },
{ model = "prop_drink_redwine",            price = 100, label = "Vörösbor" },
{ model = "vodkarow",                      price = 100, label = "Vodkasor" },
{ model = "prop_cherenkov_02",             price = 100, label = "Cherenkov" },
{ model = "prop_cherenkov_03",             price = 100, label = "Cherenkov 2" },
{ model = "prop_cocktail_glass",           price = 100, label = "Koktélos pohár" },
{ model = "prop_cs_bottle_opener",         price = 100, label = "Sörnyitó" },
{ model = "prop_food_bs_chips",            price = 100, label = "Chips" },
{ model = "prop_cs_burger_01",             price = 100, label = "Hamburger" },
{ model = "prop_cs_hand_radio",            price = 100, label = "Kézi rádió" },
{ model = "prop_cs_hotdog_01",             price = 100, label = "Hotdog" },
{ model = "prop_cs_milk_01",               price = 100, label = "Tej" },
{ model = "prop_cs_panties",               price = 100, label = "Bugyi" },
{ model = "prop_cs_steak",                 price = 100, label = "Sült hús" }

        },
    },
    ["general3"] = {
    label = "Véletlenszerű",
    items = {
        { model = "v_ret_csr_bin",            price = 100,  label = "Szemetes" },
        { model = "v_ret_fh_wickbskt",        price = 100,  label = "Kosár" },
        { model = "v_ret_gc_bag01",           price = 100,  label = "GC Táska 1" },
        { model = "v_ret_gc_bag02",           price = 100,  label = "GC Táska 2" },
        { model = "v_ret_gc_bin",             price = 100,  label = "GC Szemetes" },
        { model = "v_ret_gc_cashreg",         price = 100,  label = "Pénztárgép" },
        { model = "v_ret_gc_chair01",         price = 100,  label = "GC Szék 01" },
        { model = "v_ret_gc_chair02",         price = 100,  label = "GC Szék 02" },
        { model = "v_ret_gc_clock",           price = 100,  label = "Óra" },
        { model = "v_ret_hd_prod1_",          price = 100,  label = "Termék 1" },
        { model = "v_ret_hd_prod2_",          price = 100,  label = "Termék 2" },
        { model = "v_ret_hd_prod3_",          price = 100,  label = "Termék 3" },
        { model = "v_ret_hd_prod4_",          price = 100,  label = "Termék 4" },
        { model = "v_ret_hd_prod5_",          price = 100,  label = "Termék 5" },
        { model = "v_ret_hd_prod6_",          price = 100,  label = "Termék 6" },
        { model = "v_ret_hd_unit1_",          price = 100,  label = "HD Egység 1" },
        { model = "v_ret_hd_unit2_",          price = 100,  label = "HD Egység 2" },
        { model = "v_ret_ml_fridge02",        price = 100,  label = "Hűtő" },
        { model = "v_ret_ps_bag_01",          price = 100,  label = "Táska 1" },
        { model = "v_ret_ps_bag_02",          price = 100,  label = "Táska 2" },
        { model = "v_ret_ta_book1",           price = 100,  label = "Könyv 1" },
        { model = "v_ret_ta_book2",           price = 100,  label = "Könyv 2" },
        { model = "v_ret_ta_book3",           price = 100,  label = "Könyv 3" },
        { model = "v_ret_ta_book4",           price = 100,  label = "Könyv 4" },
        { model = "v_ret_ta_camera",          price = 100,  label = "Kamera" },
        { model = "v_ret_ta_firstaid",        price = 100,  label = "Elsősegély" },
        { model = "v_ret_ta_hero",            price = 100,  label = "Hős" },
        { model = "v_ret_ta_mag1",            price = 100,  label = "Magazin 1" },
        { model = "v_ret_ta_mag2",            price = 100,  label = "Magazin 2" },
        { model = "v_ret_ta_skull",           price = 100,  label = "Koponya" },
        { model = "prop_acc_guitar_01",       price = 100,  label = "Gitár" },
        { model = "prop_amb_handbag_01",      price = 100,  label = "Kézitáska" },
        { model = "prop_attache_case_01",     price = 100,  label = "Aktatáska" },
        { model = "prop_big_bag_01",          price = 100,  label = "Nagy táska" },
        { model = "prop_bonesaw",             price = 100,  label = "Csontfűrész" },
        { model = "prop_cs_fertilizer",       price = 100,  label = "Műtrágya" },
        { model = "prop_cs_shopping_bag",     price = 100,  label = "Bevásárlótáska" },
        { model = "prop_cs_vial_01",          price = 100,  label = "Fiola" },
        { model = "prop_defilied_ragdoll_01", price = 100,  label = "Bábfigura" },
        { model = "v_res_fa_book03",          price = 100,  label = "Kámaszútra könyv" },
        { model = "prop_weight_rack_02",      price = 500,  label = "Súlyzótartó" },
        { model = "prop_weight_bench_02",     price = 500,  label = "Fekpad súlyzózáshoz" },
        { model = "prop_tool_broom",          price = 100,  label = "Seprű" },
        { model = "prop_fire_exting_2a",      price = 100,  label = "Porral oltó" },
        { model = "v_res_vacuum",             price = 100,  label = "Porszívó" },
        { model = "v_ret_gc_fan",             price = 100,  label = "Ventilátor" },
        { model = "prop_paint_stepl01b",      price = 100,  label = "Létra" },
        { model = "bkr_prop_weed_bucket_01b", price = 100,  label = "Műtrágya (vödör)" },
        { model = "v_club_vusnaketank",       price = 500,  label = "Terrárium" },
        { model = "prop_pooltable_02",        price = 1500, label = "Biliárdasztal" },
        { model = "prop_pool_rack_02",        price = 100,  label = "Dákótartó" },
        { model = "v_club_vu_deckcase",       price = 1000, label = "DJ szett" },
        { model = "v_corp_servercln",         price = 1000, label = "Szerverállvány" }
    },
},

    ["general4"] = {
    label = "Véletlenszerű 2",
    items = {
        { model = "prop_dummy_01",             price = 100, label = "Bábu" },
        { model = "prop_egg_clock_01",         price = 100, label = "Tojásóra" },
        { model = "prop_el_guitar_01",         price = 100, label = "Elektromos gitár 1" },
        { model = "prop_el_guitar_02",         price = 100, label = "Elektromos gitár 2" },
        { model = "prop_el_guitar_03",         price = 100, label = "Elektromos gitár 3" },
        { model = "prop_feed_sack_01",         price = 100, label = "Takarmányzsák" },
        { model = "prop_floor_duster_01",      price = 100, label = "Padlótisztító" },
        { model = "prop_fruit_basket",         price = 100, label = "Gyümölcskosár" },
        { model = "prop_f_duster_02",          price = 100, label = "Portörlő" },
        { model = "prop_grapes_02",            price = 100, label = "Szőlő" },
        { model = "prop_hotel_clock_01",       price = 100, label = "Hotel óra" },
        { model = "prop_idol_case_01",         price = 100, label = "Relikviatartó" },
        { model = "prop_jewel_02a",            price = 100, label = "Ékszer" },
        { model = "prop_jewel_02b",            price = 100, label = "Ékszer" },
        { model = "prop_jewel_02c",            price = 100, label = "Ékszer" },
        { model = "prop_jewel_03a",            price = 100, label = "Ékszer" },
        { model = "prop_jewel_03b",            price = 100, label = "Ékszer" },
        { model = "prop_jewel_04a",            price = 100, label = "Ékszer" },
        { model = "prop_jewel_04b",            price = 100, label = "Ékszer" },
        { model = "prop_j_disptray_01",        price = 100, label = "Kijelző tálca" },
        { model = "prop_j_disptray_01b",       price = 100, label = "Kijelző tálca" },
        { model = "prop_j_disptray_02",        price = 100, label = "Kijelző tálca" },
        { model = "prop_j_disptray_03",        price = 100, label = "Kijelző tálca" },
        { model = "prop_j_disptray_04",        price = 100, label = "Kijelző tálca" },
        { model = "prop_j_disptray_04b",       price = 100, label = "Kijelző tálca" },
        { model = "prop_j_disptray_05",        price = 100, label = "Kijelző tálca" },
        { model = "prop_j_disptray_05b",       price = 100, label = "Kijelző tálca" },
        { model = "prop_ld_greenscreen_01",    price = 100, label = "Zöld háttér" },
        { model = "prop_ld_handbag",           price = 100, label = "Kézitáska" },
        { model = "prop_ld_jerrycan_01",       price = 100, label = "Benzinkanna" },
        { model = "prop_ld_keypad_01",         price = 100, label = "Billentyűzet 1" },
        { model = "prop_ld_keypad_01b",        price = 100, label = "Billentyűzet 2" },
        { model = "prop_ld_suitcase_01",       price = 100, label = "Bőrönd 1" },
        { model = "prop_ld_suitcase_02",       price = 100, label = "Bőrönd 2" },
        { model = "hei_p_attache_case_shut",   price = 100, label = "Bőrönd 3" },
        { model = "prop_mr_rasberryclean",     price = 100, label = "Raspberry plüss" },
        { model = "prop_paper_bag_01",         price = 100, label = "Papírzacskó" },
        { model = "prop_shopping_bags01",      price = 100, label = "Bevásárlótáskák" },
        { model = "prop_shopping_bags02",      price = 100, label = "Bevásárlótáskák 2" },
        { model = "prop_yoga_mat_01",          price = 100, label = "Jógaszőnyeg 1" },
        { model = "prop_yoga_mat_02",          price = 100, label = "Jógaszőnyeg 2" },
        { model = "prop_yoga_mat_03",          price = 100, label = "Jógaszőnyeg 3" },
        { model = "p_ld_sax",                  price = 100, label = "Szaxofon" },
        { model = "p_ld_soc_ball_01",          price = 100, label = "Focilabda" },
        { model = "p_watch_01",                price = 100, label = "Óra 1" },
        { model = "p_watch_02",                price = 100, label = "Óra 2" },
        { model = "p_watch_03",                price = 100, label = "Óra 3" },
        { model = "p_watch_04",                price = 100, label = "Óra 4" },
        { model = "p_watch_05",                price = 100, label = "Óra 5" },
        { model = "p_watch_06",                price = 100, label = "Óra 6" },
        { model = "apa_mp_h_acc_candles_01",   price = 100, label = "Gyertya" },
        { model = "apa_mp_h_acc_candles_02",   price = 100, label = "Gyertya 2" },
        { model = "apa_mp_h_acc_candles_04",   price = 100, label = "Gyertya 3" },
        { model = "apa_mp_h_acc_candles_06",   price = 100, label = "Gyertya 4" },
        { model = "apa_mp_h_acc_fruitbowl_02", price = 100, label = "Gyümölcstál" },
        { model = "apa_mp_h_acc_tray_01",      price = 100, label = "Tálca" },
        { model = "prop_bskball_01",           price = 100, label = "Kosárlabda" },
        { model = "prop_cs_wrench",            price = 100, label = "Csavarkulcs" },
        { model = "prop_cs_bowie_knife",       price = 100, label = "Bowie kés" },
        { model = "prop_w_me_hatchet",         price = 100, label = "Fejsze" }
    },
},

["small"] = {
    label = "Dísztárgyak",
    items = {
        { model = "v_res_r_figcat",               price = 300, label = "Macska figura" },
        { model = "v_res_r_figclown",             price = 300, label = "Bohóc figura" },
        { model = "v_res_r_figauth2",             price = 300, label = "Író figura" },
        { model = "v_res_r_figfemale",            price = 300, label = "Női figura" },
        { model = "v_res_r_figflamenco",          price = 300, label = "Flamenco táncos figura" },
        { model = "v_res_r_figgirl",              price = 300, label = "Kislány figura" },
        { model = "v_res_r_figgirlclown",         price = 300, label = "Kislány bohóc figura" },
        { model = "v_res_r_figoblisk",            price = 300, label = "Obeliszk figura" },
        { model = "v_res_r_figpillar",            price = 300, label = "Oszlop figura" },
        { model = "v_res_r_teapot",               price = 300, label = "Teáskanna" },
        { model = "v_res_sculpt_dec",             price = 300, label = "Szobor 1" },
        { model = "v_res_sculpt_decd",            price = 300, label = "Szobor 2" },
        { model = "v_res_sculpt_dece",            price = 300, label = "Szobor 3" },
        { model = "v_res_sculpt_decf",            price = 300, label = "Szobor 4" },
        { model = "v_res_skateboard",             price = 300, label = "Gördeszka" },
        { model = "v_res_sketchpad",              price = 300, label = "Rajztömb" },
        { model = "v_res_tissues",                price = 300, label = "Papírzsebkendő" },
        { model = "v_res_tre_basketmess",         price = 300, label = "Kosár" },
        { model = "v_res_tre_bin",                price = 300, label = "Szemetes" },
        { model = "v_res_tre_cushiona",           price = 300, label = "Párna 1" },
        { model = "v_res_tre_cushionb",           price = 300, label = "Párna 2" },
        { model = "v_res_tre_cushionc",           price = 300, label = "Párna 3" },
        { model = "v_res_tre_cushiond",           price = 300, label = "Párna 4" },
        { model = "v_res_tre_cushnscuzb",         price = 300, label = "Párna 5" },
        { model = "v_res_tre_cushnscuzd",         price = 300, label = "Párna 6" },
        { model = "v_res_tre_fruitbowl",          price = 300, label = "Gyümölcstál" },
        { model = "v_med_p_sideboard",            price = 300, label = "Komód" },
        { model = "prop_idol_01",                 price = 100, label = "Bálvány 1" },
        { model = "v_res_r_fighorsestnd",         price = 300, label = "Fekete ló figura" },
        { model = "v_res_r_fighorse",             price = 300, label = "Nagy ló figura" },
        { model = "v_res_r_figdancer",            price = 300, label = "Táncos figura" },
        { model = "v_res_fa_idol02",              price = 300, label = "Elefánt figura" },
        { model = "v_res_m_statue",               price = 300, label = "Szobor" },
        { model = "v_20_ornaeagle",               price = 300, label = "Sas figura" },
        { model = "v_med_p_vaseround",            price = 300, label = "Kerek váza" },
        { model = "ex_mp_h_acc_vase_05",          price = 300, label = "Lila váza" },
        { model = "apa_mp_h_acc_dec_head_01",     price = 300, label = "Művészeti alkotás" },
        { model = "apa_mp_h_acc_dec_sculpt_02",   price = 300, label = "Művészeti alkotás 2" },
        { model = "ex_mp_h_acc_dec_plate_02",     price = 300, label = "Művészeti alkotás 3" },
        { model = "apa_mp_h_acc_bowl_ceramic_01", price = 300, label = "Kerámia tál" },
        { model = "apa_mp_h_acc_dec_plate_01",    price = 300, label = "Tál 2" },
        { model = "apa_mp_h_acc_vase_01",         price = 300, label = "Fekete-fehér váza" },
        { model = "apa_mp_h_acc_vase_02",         price = 300, label = "Piros váza" },
        { model = "apa_mp_h_acc_vase_05",         price = 300, label = "Váza" },
        { model = "apa_mp_h_acc_vase_06",         price = 300, label = "Fekete-fehér váza 2" }
    },
},

 ["electronics"] = {
    label = "Elektronika",
    items = {
        { model = "prop_trailr_fridge",                price = 300,  label = "Régi hűtőszekrény" },
        { model = "v_res_fh_speaker",                  price = 300,  label = "Hangfal" },
        { model = "v_res_fh_speakerdock",              price = 300,  label = "Hangfal dokkoló" },
        { model = "v_res_fh_bedsideclock",             price = 300,  label = "Ébresztőóra" },
        { model = "v_res_fa_phone",                    price = 300,  label = "Telefon" },
        { model = "v_res_lest_bigscreen",              price = 300,  label = "Nagyképernyős TV" },
        { model = "v_res_lest_monitor",                price = 300,  label = "Monitor" },
        { model = "v_res_tre_mixer",                   price = 300,  label = "Mixer" },
        { model = "prop_cs_cctv",                      price = 100,  label = "Biztonsági kamera" },
        { model = "prop_ld_lap_top",                   price = 100,  label = "Laptop" },
        { model = "prop_ld_monitor_01",                price = 100,  label = "Monitor" },
        { model = "prop_speaker_05",                   price = 500,  label = "Fali hangszóró" },
        { model = "prop_tv_flat_03b",                  price = 1000, label = "Kis lapos TV" },
        { model = "prop_laptop_01a",                   price = 750,  label = "Nyitott laptop" },
        { model = "prop_tv_flat_michael",              price = 3000, label = "Függesztett lapos TV" },
        { model = "prop_dyn_pc",                       price = 1000, label = "Számítógép" },
        { model = "prop_keyboard_01b",                 price = 100,  label = "Billentyűzet" },
        { model = "prop_mouse_01b",                    price = 100,  label = "Egér" },
        { model = "v_ret_gc_phone",                    price = 100,  label = "Irodai telefon" },
        { model = "prop_tv_flat_01",                   price = 5000, label = "Nagy lapos TV" },
        { model = "prop_arcade_01",                    price = 5000, label = "Játékgép" },
        { model = "prop_console_01",                   price = 250,  label = "Játékkonzol" },
        { model = "v_res_tre_dvdplayer",               price = 250,  label = "DVD lejátszó" },
        { model = "prop_speaker_08",                   price = 500,  label = "Fa hangszóró" },
        { model = "prop_cctv_mon_02",                  price = 300,  label = "Kamera monitor" },
        { model = "prop_tv_flat_02",                   price = 2500, label = "Álló lapos TV" },
        { model = "prop_cctv_cam_01a",                 price = 300,  label = "Biztonsági kamera 2" },
        { model = "prop_dest_cctv_02",                 price = 300,  label = "Kamera monitor 2" },
        { model = "prop_cctv_cam_07a",                 price = 300,  label = "Biztonsági kamera 3" },
        { model = "apa_mp_h_str_avunits_04",           price = 5500, label = "TV bútor" },
        { model = "apa_mp_h_str_avunits_01",           price = 5500, label = "TV bútor 2" },
        { model = "v_club_vu_deckcase",                price = 1000, label = "DJ szett" },
        { model = "v_corp_servercln",                  price = 1000, label = "Szerverállvány" },
        { model = "apa_mp_h_str_avunitl_01_b",         price = 5500, label = "TV bútor 3" },
        { model = "apa_mp_h_str_avunitl_04",           price = 5500, label = "TV bútor 4" },
        { model = "apa_mp_h_str_avunitm_01",           price = 5500, label = "TV bútor 5" },
        { model = "apa_mp_h_str_avunitm_03",           price = 5500, label = "TV bútor 6" },
        { model = "apa_mp_h_str_avunits_04",           price = 5500, label = "TV bútor 7" },
        { model = "v_res_printer",                     price = 300,  label = "Nyomtató" },
        { model = "apa_mp_h_acc_phone_01",             price = 100,  label = "Retro telefon" },
        { model = "v_res_mousemat",                    price = 300,  label = "Egérpad" },
        { model = "v_res_pcheadset",                   price = 300,  label = "Fejhallgató" },
        { model = "v_res_pcspeaker",                   price = 300,  label = "PC hangszóró" },
        { model = "ba_prop_battle_club_speaker_small", price = 500,  label = "Kis hangfal" },
        { model = "ba_prop_battle_club_speaker_med",   price = 750,  label = "Közepes hangfal" },
        { model = "ba_prop_battle_club_speaker_large", price = 1000, label = "Nagy hangfal" },
        { model = "v_res_pcspeaker",                   price = 300,  label = "PC hangszóró" },
        { model = "v_res_pcwoofer",                    price = 300,  label = "PC mélynyomó" },
        { model = "prop_controller_01",                price = 300,  label = "Kontroller" },
        { model = "prop_cs_remote_01",                 price = 300,  label = "Távirányító" },
        { model = "prop_portable_hifi_01",             price = 300,  label = "Rádió" },
        { model = "prop_dj_deck_02",                   price = 300,  label = "DJ asztal" },
        { model = "prop_speaker_01",                   price = 300,  label = "Hangfal" }
    },
},

 ["lighting"] = {
    label = "Világítás",
    items = {
        { model = "v_corp_cd_desklamp",                price = 100, label = "Íróasztali céges lámpa" },
        { model = "v_res_desklamp",                    price = 100, label = "Íróasztali lámpa" },
        { model = "v_res_d_lampa",                     price = 100, label = "Lámpa AA" },
        { model = "v_res_fa_lamp1on",                  price = 100, label = "Lámpa 1" },
        { model = "v_res_fh_floorlamp",                price = 100, label = "Állólámpa" },
        { model = "v_res_fh_lampa_on",                 price = 100, label = "Lámpa 2" },
        { model = "v_res_j_tablelamp1",                price = 100, label = "Asztali lámpa" },
        { model = "v_res_j_tablelamp2",                price = 100, label = "Asztali lámpa 2" },
        { model = "v_res_mdbedlamp",                   price = 100, label = "Éjjeli lámpa" },
        { model = "v_res_mplanttongue",                price = 100, label = "Növényes lámpa" },
        { model = "v_res_mtblelampmod",                price = 100, label = "Asztali lámpa 3" },
        { model = "v_res_m_lampstand",                 price = 100, label = "Lámpaállvány" },
        { model = "v_res_m_lampstand2",                price = 100, label = "Lámpaállvány 2" },
        { model = "v_res_m_lamptbl",                   price = 100, label = "Asztali lámpa 4" },
        { model = "v_res_tre_lightfan",                price = 100, label = "Ventilátoros lámpa" },
        { model = "v_res_tre_talllamp",                price = 100, label = "Magas lámpa" },
        { model = "v_ret_fh_walllighton",              price = 100, label = "Fali lámpa" },
        { model = "v_ret_gc_lamp",                     price = 100, label = "GC lámpa" },
        { model = "prop_dummy_light",                  price = 100, label = "Villogó lámpa" },
        { model = "prop_ld_cont_light_01",             price = 100, label = "Oldalfali lámpa" },
        { model = "V_44_D_emis",                       price = 100, label = "Tesztlámpa" },
        { model = "prop_wall_light_07a",               price = 100, label = "Lámpás" },
        { model = "prop_wall_light_01a",               price = 100, label = "Olcsó lámpa" },
        { model = "v_serv_tu_light2_",                 price = 100, label = "Ipari lámpa" },
        { model = "v_serv_tu_light3_",                 price = 100, label = "Ipari lámpa 2" },
        { model = "ba_prop_battle_lights_ceiling_l_a", price = 300, label = "Függőlámpa" },
        { model = "v_med_p_floorlamp",                 price = 300, label = "Nagy lámpa" },
        { model = "v_club_vu_lamp",                    price = 100, label = "Kis lámpa" },
        { model = "ba_prop_battle_lights_wall_l_a",    price = 100, label = "Fali lámpa" },
        { model = "ba_prop_battle_lights_ceiling_l_c", price = 300, label = "Függőlámpa 2" },
        { model = "ba_prop_battle_lights_ceiling_l_b", price = 300, label = "Csillár 2" },
        { model = "ba_prop_battle_lights_wall_l_c",    price = 100, label = "Fali lámpa 2" },
        { model = "ba_prop_battle_lights_wall_l_b",    price = 100, label = "Fali lámpa 3" },
        { model = "hei_heist_lit_lightpendant_02",     price = 300, label = "Függőlámpa 3" },
        { model = "prop_oldlight_01b",                 price = 100, label = "Fali lámpa 4" },
        { model = "apa_mp_h_lit_floorlampnight_07",    price = 100, label = "Kék lámpa" },
        { model = "apa_mp_h_ceiling_light_01",         price = 100, label = "Irodai lámpa" },
        { model = "apa_mp_h_ceiling_light_01_day",     price = 100, label = "Irodai lámpa 2" },
        { model = "apa_mp_h_ceiling_light_02",         price = 100, label = "Mennyezeti lámpa" },
        { model = "apa_mp_h_ceiling_light_02_day",     price = 100, label = "Mennyezeti lámpa 2" },
        { model = "ba_prop_battle_lights_ceiling_l_d", price = 100, label = "Irodai lámpa 3" },
        { model = "ba_prop_battle_lights_ceiling_l_f", price = 100, label = "Mennyezeti lámpa 3" },
        { model = "ba_prop_battle_lights_ceiling_l_e", price = 100, label = "Mennyezeti lámpa 4" },
        { model = "apa_mp_h_floorlamp_a",              price = 100, label = "Állólámpa" },
        { model = "apa_mp_h_floorlamp_b",              price = 100, label = "Állólámpa 2" },
        { model = "apa_mp_h_floorlamp_c",              price = 100, label = "Állólámpa 3" },
        { model = "apa_mp_h_floor_lamp_int_08",        price = 100, label = "Állólámpa 4" },
        { model = "apa_mp_h_lampbulb_multiple_a",      price = 100, label = "Mennyezeti lámpa 5" },
        { model = "apa_mp_h_lit_floorlamp_02",         price = 100, label = "Állólámpa 5" },
        { model = "apa_mp_h_lit_floorlampnight_14",    price = 100, label = "Állólámpa 6" },
        { model = "apa_mp_h_lit_floorlamp_03",         price = 100, label = "Állólámpa 7" },
        { model = "apa_mp_h_lit_floorlamp_06",         price = 100, label = "Állólámpa 8" },
        { model = "apa_mp_h_lit_floorlamp_10",         price = 100, label = "Állólámpa 9" },
        { model = "apa_mp_h_lit_floorlamp_13",         price = 100, label = "Állólámpa 10" },
        { model = "apa_mp_h_lit_floorlamp_17",         price = 100, label = "Állólámpa 11" },
        { model = "apa_mp_h_lit_lamptablenight_16",    price = 100, label = "Éjjeli fény" },
        { model = "apa_mp_h_lit_lamptablenight_24",    price = 100, label = "Éjjeli fény 2" },
        { model = "apa_mp_h_lit_lamptable_005",        price = 100, label = "Éjjeli fény 3" },
        { model = "apa_mp_h_lit_lamptable_04",         price = 100, label = "Éjjeli fény 4" },
        { model = "apa_mp_h_lit_lamptable_09",         price = 100, label = "Éjjeli fény 5" },
        { model = "apa_mp_h_lit_lamptable_14",         price = 100, label = "Éjjeli fény 6" },
        { model = "apa_mp_h_lit_lamptable_17",         price = 100, label = "Éjjeli fény 7" },
        { model = "apa_mp_h_yacht_table_lamp_01",      price = 100, label = "Éjjeli fény 8" }
    },
},

["tables"] = {
    label = "Asztalok",
    items = {
        { model = "v_res_d_coffeetable",            price = 500,  label = "Kávézóasztal 1" },
        { model = "v_res_d_roundtable",             price = 500,  label = "Kerek asztal" },
        { model = "v_res_d_smallsidetable",         price = 500,  label = "Kis oldalsó asztal" },
        { model = "v_res_fh_coftablea",             price = 500,  label = "Asztal A" },
        { model = "v_res_fh_coftableb",             price = 500,  label = "Asztal B" },
        { model = "v_res_fh_coftbldisp",            price = 500,  label = "Asztal C" },
        { model = "v_res_fh_diningtable",           price = 500,  label = "Étkezőasztal" },
        { model = "v_res_j_coffeetable",            price = 500,  label = "Kávézóasztal 2" },
        { model = "v_res_j_lowtable",               price = 500,  label = "Alacsony asztal" },
        { model = "v_res_mdbedtable",               price = 500,  label = "Ágy melletti asztal" },
        { model = "v_res_mddesk",                   price = 500,  label = "Íróasztal" },
        { model = "v_res_msidetblemod",             price = 500,  label = "Oldalsó asztal" },
        { model = "v_res_m_console",                price = 500,  label = "Konzol asztal" },
        { model = "v_res_m_dinetble_replace",       price = 500,  label = "Étkezőasztal 2" },
        { model = "v_res_m_h_console",              price = 500,  label = "Konzol H asztal" },
        { model = "v_res_m_stool",                  price = 500,  label = "Szék?" },
        { model = "v_res_tre_sideboard",            price = 500,  label = "Oldalsó szekrény" },
        { model = "v_res_tre_table2",               price = 500,  label = "Asztal 2" },
        { model = "v_res_tre_tvstand",              price = 500,  label = "TV asztal" },
        { model = "v_res_tre_tvstand_tall",         price = 500,  label = "Magas TV asztal" },
        { model = "v_med_p_coffeetable",            price = 500,  label = "Med Kávézóasztal" },
        { model = "v_med_p_desk",                   price = 500,  label = "Med Íróasztal" },
        { model = "prop_yacht_table_01",            price = 100,  label = "Jacht asztal 1" },
        { model = "prop_yacht_table_02",            price = 100,  label = "Jacht asztal 2" },
        { model = "prop_yacht_table_03",            price = 100,  label = "Jacht asztal 3" },
        { model = "v_ret_csr_table",                price = 100,  label = "CSR asztal" },
        { model = "v_res_mconsoletrad",             price = 250,  label = "Magas oldalsó asztal" },
        { model = "v_ilev_liconftable_sml",         price = 500,  label = "Iroda asztal" },
        { model = "v_ret_tablesml",                 price = 350,  label = "Oldalsó asztal Marillaux" },
        { model = "apa_mp_h_yacht_coffee_table_02", price = 500,  label = "Barna kávézóasztal" },
        { model = "apa_mp_h_yacht_side_table_01",   price = 300,  label = "Barna oldalsó asztal" },
        { model = "apa_mp_h_yacht_side_table_02",   price = 300,  label = "Kerek oldalsó asztal" },
        { model = "apa_mp_h_tab_sidelrg_04",        price = 300,  label = "Kerek oldalsó asztal 2" },
        { model = "v_club_vu_table",                price = 300,  label = "Fedett asztal" },
        { model = "apa_mp_h_tab_sidelrg_07",        price = 500,  label = "Üveg kávézóasztal" },
        { model = "bkr_prop_weed_table_01b",        price = 100,  label = "Clap asztal" },
        { model = "ba_prop_int_trad_table",         price = 300,  label = "Álló asztal" },
        { model = "apa_mp_h_str_sideboards_02",     price = 750,  label = "Üveg oldalsó asztal" },
        { model = "apa_mp_h_yacht_coffee_table_01", price = 750,  label = "Modern kávézóasztal" },
        { model = "apa_mp_h_din_table_04",          price = 1000, label = "Üveg étkezőasztal" },
        { model = "xm_prop_base_staff_desk_01",     price = 5000, label = "Íróasztal + beállítás" },
        { model = "apa_mp_h_tab_coffee_07",         price = 1000, label = "Háromszög oldalsó asztal" },
        { model = "apa_mp_h_tab_coffee_08",         price = 1000, label = "Fehér oldalsó asztal" },
        { model = "apa_mp_h_tab_sidelrg_01",        price = 1000, label = "Üveg oldalsó asztal" },
        { model = "apa_mp_h_tab_sidelrg_02",        price = 1000, label = "Üveg oldalsó asztal 2" },
        { model = "apa_mp_h_tab_sidesml_01",        price = 1000, label = "Hajlított asztal" },
        { model = "ba_prop_int_edgy_table_01",      price = 500,  label = "Márvány asztal" },
        { model = "ba_prop_int_edgy_table_02",      price = 500,  label = "Magas márvány asztal" },
        { model = "apa_mp_h_tab_sidelrg_01",        price = 1000, label = "Üveg oldalsó asztal" },
        { model = "xm_prop_lab_desk_01",            price = 1000, label = "Labor asztal" }
    },
},

 ["plants"] = {
    label = "Növények",
    items = {
        { model = "prop_fib_plant_01",            price = 150, label = "Szálas Növény" },
        { model = "v_corp_bombplant",             price = 170, label = "Bombanövény" },
        { model = "v_res_mflowers",               price = 170, label = "Virágok" },
        { model = "v_res_mvasechinese",           price = 170, label = "Kínai Növény" },
        { model = "v_res_m_bananaplant",          price = 170, label = "Banán Növény" },
        { model = "v_res_m_palmplant1",           price = 170, label = "Pálma Növény" },
        { model = "v_res_m_palmstairs",           price = 170, label = "Pálma Növény 2" },
        { model = "v_res_m_urn",                  price = 170, label = "Urnás Növény" },
        { model = "v_res_rubberplant",            price = 170, label = "Gumi Növény" },
        { model = "v_res_tre_plant",              price = 170, label = "Növény" },
        { model = "v_res_tre_tree",               price = 170, label = "Fa Növény" },
        { model = "v_med_p_planter",              price = 170, label = "Virágcserép" },
        { model = "v_ret_flowers",                price = 100, label = "Virágok" },
        { model = "v_ret_j_flowerdisp",           price = 100, label = "Virágok 1" },
        { model = "v_ret_j_flowerdisp_white",     price = 100, label = "Virágok 2" },
        { model = "v_res_m_vasefresh",            price = 300, label = "Friss Virágcserép" },
        { model = "v_res_rosevasedead",           price = 300, label = "Halott Rózsa Növény 2" },
        { model = "v_res_exoticvase",             price = 300, label = "Exotikus Virágcserép" },
        { model = "v_res_rosevase",               price = 300, label = "Rózsa Növény" },
        { model = "prop_pot_plant_6a",            price = 300, label = "Lógó Növény" },
        { model = "prop_pot_plant_02a",           price = 300, label = "Virágcserép" },
        { model = "apa_mp_h_acc_plant_palm_01",   price = 300, label = "Pálma Növény" },
        { model = "prop_plant_interior_05a",      price = 300, label = "Virágdoboz" },
        { model = "prop_plant_int_01a",           price = 300, label = "Növény 1" },
        { model = "prop_plant_int_01b",           price = 300, label = "Növény 2" },
        { model = "prop_plant_int_02a",           price = 300, label = "Növény 3" },
        { model = "prop_plant_int_02b",           price = 300, label = "Növény 4" },
        { model = "prop_plant_int_03a",           price = 300, label = "Növény 5" },
        { model = "prop_plant_int_03b",           price = 300, label = "Növény 6" },
        { model = "prop_plant_int_03c",           price = 300, label = "Növény 7" },
        { model = "prop_plant_int_04a",           price = 300, label = "Növény 8" },
        { model = "prop_plant_int_04c",           price = 300, label = "Növény 9" },
        { model = "prop_plant_int_05b",           price = 300, label = "Virágdoboz 2" },
        { model = "prop_pot_plant_01a",           price = 300, label = "Növény Cserép 2" },
        { model = "prop_pot_plant_01b",           price = 300, label = "Növény Cserép 3" },
        { model = "prop_pot_plant_01c",           price = 300, label = "Növény Cserép 4" },
        { model = "prop_pot_plant_01d",           price = 300, label = "Növény Cserép 5" },
        { model = "prop_pot_plant_01e",           price = 300, label = "Növény Cserép 6" },
        { model = "prop_pot_plant_03b",           price = 300, label = "Növény Cserép 7" },
        { model = "prop_pot_plant_05a",           price = 300, label = "Növény Cserép 8" },
        { model = "prop_pot_plant_05b",           price = 300, label = "Növény Cserép 9" },
        { model = "p_int_jewel_plant_01",         price = 300, label = "Növény Cserép 10" },
        { model = "p_int_jewel_plant_02",         price = 300, label = "Növény Cserép 11" },
        { model = "apa_mp_h_acc_vase_flowers_01", price = 300, label = "Növény Cserép 12" },
        { model = "apa_mp_h_acc_vase_flowers_02", price = 300, label = "Növény Cserép 13" },
        { model = "apa_mp_h_acc_vase_flowers_03", price = 300, label = "Növény Cserép 14" },
        { model = "apa_mp_h_acc_vase_flowers_04", price = 300, label = "Növény Cserép 15" }
    },
},

    ["kitchen"] = {
        label = "Konyha",
        items = {
            [1] = { model = "prop_washer_01", price = 150, label = "Mosógép 1" },
            [2] = { model = "prop_washer_02", price = 150, label = "Mosógép 2" },
            [3] = { model = "prop_washer_03", price = 150, label = "Mosógép 3" },
            [4] = { model = "prop_washing_basket_01", price = 150, label = "Mosó Kosár" },
            [5] = { model = "v_res_fridgemoda", price = 150, label = "Hűtő 1" },
            [6] = { model = "v_res_fridgemodsml", price = 150, label = "Hűtő 2" },
            [7] = { model = "prop_fridge_01", price = 150, label = "Hűtő 3" },
            [8] = { model = "prop_fridge_03", price = 150, label = "Hűtő 4" },
            [9] = { model = "prop_cooker_03", price = 150, label = "Tűzhely" },
            [10] = { model = "prop_micro_01", price = 150, label = "Mikrohullámú 1" },
            [11] = { model = "prop_micro_02", price = 150, label = "Mikrohullámú 2" },
            [12] = { model = "prop_wok", price = 150, label = "Wok" },
            [13] = { model = "v_res_cakedome", price = 150, label = "Torta Tálca" },
            [14] = { model = "v_res_fa_chopbrd", price = 150, label = "Vágódeszka" },
            [15] = { model = "v_res_mutensils", price = 150, label = "Konyhai Eszközök" },
            [16] = { model = "v_res_pestle", price = 150, label = "Mozsár" },
            [17] = { model = "v_ret_ta_paproll", price = 150, label = "Papírtörlő 1" },
            [18] = { model = "v_ret_ta_paproll2", price = 150, label = "Papírtörlő 2" },
            [19] = { model = "v_ret_fh_pot01", price = 150, label = "Tál 1" },
            [20] = { model = "v_ret_fh_pot02", price = 150, label = "Tál 2" },
            [21] = { model = "v_ret_fh_pot05", price = 150, label = "Tál 3" },
            [22] = { model = "prop_pot_03", price = 150, label = "Tál 4" },
            [23] = { model = "prop_pot_04", price = 150, label = "Tál 5" },
            [24] = { model = "prop_pot_05", price = 150, label = "Tál 6" },
            [25] = { model = "prop_pot_06", price = 150, label = "Tál 7" },
            [26] = { model = "prop_pot_rack", price = 150, label = "Tálaló Állvány" },
            [27] = { model = "prop_kitch_juicer", price = 150, label = "Facsaró" },
            [28] = { model = "v_res_ovenhobmod", price = 1000, label = "Sütő" },
            [29] = { model = "v_res_mkniferack", price = 100, label = "Késtartó" },
            [30] = { model = "v_res_mchopboard", price = 100, label = "Vágódeszka" },
            [31] = { model = "prop_cs_kitchen_cab_l", price = 750, label = "Konyhaszekrény Széles" },
            [32] = { model = "prop_cs_kitchen_cab_r", price = 500, label = "Konyhaszekrény Kicsi" },
            [33] = { model = "prop_cs_kitchen_cab_r", price = 500, label = "Konyhaszekrény Kicsi" },
            [34] = { model = "v_res_tre_fridge", price = 500, label = "Hűtő" },
            [35] = { model = "apa_mp_h_acc_coffeemachine_01", price = 500, label = "Kávéfőző" },
            [36] = { model = "p_new_j_counter_02", price = 500, label = "Pult" },
            [37] = { model = "prop_bar_pump_09", price = 500, label = "Pumpa 1" },
            [38] = { model = "prop_bar_pump_01", price = 500, label = "Pumpa 2" },
            [39] = { model = "prop_chip_fryer", price = 500, label = "Chips Sütő" },
            [40] = { model = "prop_cleaver", price = 500, label = "Késsel" },
            [41] = { model = "prop_coffee_mac_02", price = 500, label = "Kávéfőző" },
            [42] = { model = "prop_coffee_mac_01", price = 500, label = "Kávéfőző 2" },
            [43] = { model = "prop_cs_fork", price = 500, label = "Villás" },
            [44] = { model = "prop_cs_sink_filler", price = 500, label = "Mosogatótöltő" },
            [45] = { model = "prop_toaster_01", price = 500, label = "Pirító" },
            [46] = { model = "prop_cs_plate_01", price = 500, label = "Tányér" },
            [47] = { model = "prop_foodprocess_01", price = 500, label = "Étel Aprító" },
            [48] = { model = "prop_food_sugarjar", price = 500, label = "Cukortartó" },
            [49] = { model = "prop_juice_dispenser", price = 500, label = "Italadagoló" },
            [50] = { model = "prop_knife_stand", price = 500, label = "Késállvány" },
            [51] = { model = "prop_knife", price = 500, label = "Kés 2" },
            [52] = { model = "prop_micro_04", price = 500, label = "Mikrohullámú 4" },
            [53] = { model = "v_ret_fh_plate3", price = 500, label = "Tányér 5" },
            [54] = { model = "v_ilev_tt_plate01", price = 500, label = "Tányér 6" },
            [55] = { model = "v_res_fa_grater", price = 500, label = "Reszelő" },
            [56] = { model = "v_res_tt_pizzaplate", price = 500, label = "Pizza Tányér" },
            [57] = { model = "v_ret_247_ketchup2", price = 500, label = "Ketchup" }
        },
    },

 ["bathroom"] = {
    label = "Fürdőszoba",
    items = {
        [1] = { model = "prop_ld_toilet_01", price = 100, label = "WC 1" },
        [2] = { model = "prop_toilet_01", price = 100, label = "WC 2" },
        [3] = { model = "prop_toilet_02", price = 100, label = "WC 3" },
        [4] = { model = "prop_sink_02", price = 100, label = "Mosdó 1" },
        [5] = { model = "prop_sink_04", price = 100, label = "Mosdó 2" },
        [6] = { model = "prop_sink_05", price = 100, label = "Mosdó 3" },
        [7] = { model = "prop_sink_06", price = 100, label = "Mosdó 4" },
        [8] = { model = "prop_soap_disp_01", price = 100, label = "Szappanadagoló" },
        [9] = { model = "prop_shower_rack_01", price = 100, label = "Zuhanytartó" },
        [10] = { model = "prop_handdry_01", price = 100, label = "Kézszárító 1" },
        [11] = { model = "prop_handdry_02", price = 100, label = "Kézszárító 2" },
        [12] = { model = "prop_towel_rail_01", price = 100, label = "Törölközőtartó 1" },
        [13] = { model = "prop_towel_rail_02", price = 100, label = "Törölközőtartó 2" },
        [14] = { model = "prop_towel_01", price = 100, label = "Törölköző 1" },
        [15] = { model = "v_res_mbtowel", price = 100, label = "Törölköző 2" },
        [16] = { model = "v_res_mbtowelfld", price = 100, label = "Törölköző 3" },
        [17] = { model = "v_res_mbath", price = 100, label = "Kád" },
        [18] = { model = "v_res_mbsink", price = 100, label = "Mosdó" },
        [19] = { model = "v_ilev_mm_faucet", price = 100, label = "Csap" },
        [20] = { model = "v_res_tre_washbasket", price = 250, label = "Mosó kosár" },
        [21] = { model = "prop_toilet_soap_02", price = 100, label = "Tálca szappan" },
        [22] = { model = "prop_bar_sink_01", price = 100, label = "Mosdó" },
        [23] = { model = "apa_mp_h_bathtub_01", price = 1000, label = "Kád" },
        [24] = { model = "prop_toilet_brush_01", price = 1000, label = "WC kefe" },
        [25] = { model = "prop_toilet_roll_01", price = 1000, label = "WC papír" },
        [26] = { model = "prop_toilet_roll_02", price = 1000, label = "WC papír 2" },
        [27] = { model = "prop_toilet_shamp_01", price = 1000, label = "Sampon" },
        [28] = { model = "prop_toilet_shamp_02", price = 1000, label = "Sampon 2" }
    },
},
["medical"] = {
    label = "Orvosi",
    items = {
        { model = "v_med_barrel", price = 750, label = "Barrel" },
        { model = "v_med_apecrate", price = 750, label = "Majom Láda" },
        { model = "v_med_apecratelrg", price = 750, label = "Majom Láda Nagy" },
        { model = "v_med_bed1", price = 750, label = "Ágy 1" },
        { model = "v_med_bed2", price = 750, label = "Ágy 2" },
        { model = "v_med_bedtable", price = 750, label = "Ágyasztal" },
        { model = "v_med_bench1", price = 750, label = "Pad 1" },
        { model = "v_med_bench2", price = 750, label = "Pad 2" },
        { model = "v_med_benchcentr", price = 750, label = "Középső Pad" },
        { model = "v_med_benchset1", price = 750, label = "Pad Szett" },
        { model = "v_med_bigtable", price = 750, label = "Nagy Asztal" },
        { model = "v_med_bin", price = 150, label = "Kuka" },
        { model = "v_med_centrifuge1", price = 750, label = "Centrifuga" },
        { model = "v_med_cooler", price = 750, label = "Hűtő" },
        { model = "v_med_cor_ceilingmonitor", price = 750, label = "Monitor" },
        { model = "v_med_cor_autopsytbl", price = 750, label = "Autopszi Asztal" },
        { model = "v_med_cor_cembin", price = 750, label = "Kuka" },
        { model = "v_med_cor_cemtrolly2", price = 750, label = "Trolley" },
        { model = "v_med_cor_chemical", price = 750, label = "Kémia" },
        { model = "v_med_cor_emblmtable", price = 750, label = "BLM Asztal" },
        { model = "v_med_cor_fileboxa", price = 750, label = "Dosszié" },
        { model = "v_med_cor_filingcab", price = 750, label = "Irattároló" },
        { model = "v_med_cor_hose", price = 750, label = "Tömlő" },
        { model = "v_med_cor_largecupboard", price = 750, label = "Nagy Szekrény" },
        { model = "v_med_cor_lightbox", price = 750, label = "Fénybox" },
        { model = "v_med_cor_medstool", price = 750, label = "Orvosi Szék" },
        { model = "v_med_cor_minifridge", price = 750, label = "Mini Hűtő" },
        { model = "v_med_cor_papertowels", price = 750, label = "Papírtörlő" },
        { model = "v_med_cor_photocopy", price = 750, label = "Fénymásoló" },
        { model = "v_med_cor_tvstand", price = 750, label = "TV Állvány" },
        { model = "v_med_cor_wallunita", price = 750, label = "Fali Szekrény" },
        { model = "v_med_examlight", price = 750, label = "Vizsgálati Fény" },
        { model = "v_med_gastank", price = 750, label = "Gáz Palack" },
        { model = "v_med_hazmatscan", price = 750, label = "Hazmat Vizsgálat" },
        { model = "v_med_hospheadwall1", price = 750, label = "Fejfal" },
        { model = "v_med_hospseating1", price = 750, label = "Ülőhely" },
        { model = "v_med_hosptable", price = 750, label = "Kórházi Asztal" },
        { model = "v_med_latexgloveboxblue", price = 50, label = "Kesztyűtartó" },
        { model = "v_med_medwastebin", price = 750, label = "Hulladéktároló" },
        { model = "v_med_oscillator3", price = 750, label = "Oszcillátor" },
        { model = "prop_ld_health_pack", price = 100, label = "Egészségcsomag" },
    },
},

["walldecoration"] = {
    label = "Fali dekoráció",
    items = {
        { model = "apa_p_h_acc_artwalll_02",      price = 1000, label = "Festmény karcokkal" },
        { model = "v_ind_cs_toolboard",           price = 500,  label = "Szerszámok" },
        { model = "apa_mp_stilts_bed_art",        price = 300,  label = "3D műalkotás" },
        { model = "ex_office_swag_paintings03",   price = 1000, label = "Festmény (földön)" },
        { model = "ex_mp_h_acc_artwallm_03",      price = 750,  label = "Absztrakt festmény" },
        { model = "ex_p_h_acc_artwallm_04",       price = 750,  label = "Absztrakt festmény 2" },
        { model = "ex_p_h_acc_artwalll_01",       price = 1250, label = "Nagy absztrakt festmény" },
        { model = "apa_p_h_acc_artwalll_03",      price = 750,  label = "Absztrakt festmény 3" },
        { model = "ex_mp_h_acc_artwallm_02",      price = 750,  label = "Absztrakt festmény 4" },
        { model = "ex_p_h_acc_artwallm_03",       price = 750,  label = "Absztrakt festmény 5" },
        { model = "apa_mp_stilts_a_study_pics",   price = 500,  label = "Festmény" },
        { model = "apa_mp_h_acc_artwallm_02",     price = 750,  label = "Absztrakt festmény 6" },
        { model = "apa_mp_h_acc_artwalll_02",     price = 750,  label = "Absztrakt festmény 7" },
        { model = "apa_mp_h_acc_artwallm_04",     price = 750,  label = "Absztrakt festmény 8" },
        { model = "prop_dart_bd_cab_01",          price = 250,  label = "Darts tábla" },
        { model = "prop_dart_bd_01",              price = 250,  label = "Darts tábla 2" },
        { model = "hei_heist_acc_artwalll_01",    price = 250,  label = "Fali dekoráció 1" },
        { model = "hei_heist_acc_artgolddisc_01", price = 250,  label = "Fali dekoráció 2" },
        { model = "hei_heist_acc_artgolddisc_02", price = 250,  label = "Fali dekoráció 3" },
        { model = "hei_heist_acc_artgolddisc_03", price = 250,  label = "Fali dekoráció 4" },
        { model = "hei_heist_acc_artgolddisc_04", price = 250,  label = "Fali dekoráció 5" },
        { model = "v_ilev_ra_doorsafe",           price = 250,  label = "Luxus dekoráció" }
    },
},

}
